### ISSUE TITLE
Assess the geographic coverage of elections data.

### ISSUE THREAD

**Issue by nbanion** [DataKind-DC/ifes-elections#18]
What geographies are included in our elections data?

Answer this question with narrative and graphics, and brainstorm the implications of your findings. Also identify questions we should ask of IFES contacts.

**Comment by varungoel123** [comment]
I will work on this one next week- How do I assign this task to myself?

**Comment by nbanion** [comment]
@varungoel123 I just assigned you and added privileges so that you should be able to modify issues. Let me know if you have any trouble.

**Comment by nbanion** [comment]
Not currently a priority.
