### ISSUE TITLE
Identify alternative election data sources.

### ISSUE THREAD

**Issue by nbanion** [DataKind-DC/ifes-elections#27]
What other election data sources are out there?

This research could be useful if we decide to use data beyond what is available via the ElectionGuide API.

**Comment by nbanion** [comment]
@varungoel123, didn't you already identify some leads?

**Comment by varungoel123** [comment]
Here is a compilation of some potentially useful ones:

https://libguides.princeton.edu/elections/foreign

**Comment by nbanion** [comment]
Great resource!

Especially interesting is the "Electoral Administration and Integrity" section. These datasets seem to describe the mechanics of elections around the world-- more than just the outcomes. They seem in line with IFES interests.

The [Perceptions of Electoral Integrity](https://dataverse.harvard.edu/dataverse/PEI) data look promising. They explicitly cover different phases of the electoral cycle. At a glance, I didn't see variables to date stamp different phases of the electoral cycle. However, we might be able to show which phases in the electoral cycle have been weak links over time. Doing so could still help IFES direct stakeholder attention to underappreciated phases, even if we can't say when or for how long those phases occur.

**Comment by sramchandani** [comment]
Nathan,

Jimmy said he does have access and he doesn't have an email from you yet

**Comment by nbanion** [comment]
I broke this issue into issues for individual datasets. They seems like good tasks for Data Jam volunteers.

**Comment by nbanion** [comment]
See #28, #29, and #31 for sources that might help us evaluate specific phases of the electoral cycle.

**Comment by nbanion** [comment]
Many of the other data sources focus on election results or the details of particular political / election systems. These data sources might help supplement the analysis, but they probably won't drive the analysis.
