### ISSUE TITLE
Evaluate the Data on International Election Monitoring Datasets

### ISSUE THREAD

**Issue by nbanion** [DataKind-DC/ifes-elections#29]
Evaluate how this dataset might help us answer our motivating questions.

https://www.icpsr.umich.edu/web/ICPSR/studies/31461/versions/V1

Read the documentation, briefly explore the data, and make a case for or against using this data source. If the data seem promising, then describe some possible uses. If not, then explain the shortcomings. If you are unsure, then write down your questions. No matter what, your investigation is valuable!

Record your findings in the discussion on this issue.

This data set comes from a collection identified on #27 .

**Comment by nbanion** [comment]
**Good potential primary data source.**

These data appear to include election monitor evaluations of different components of elections.

- Data on International Election Monitoring (DIEM): 108 countries, 1980 - 2004.
- Quality of Elections Data (QED): 172 countries, 1978 - 2004.
- Supplementary Election Data: 182 countries, 1975 - 2004.

The documentation looks comprehensive, too.

**One big problem:** No matter which link I click, the download seems to only include the documentation and not the data.

**Comment by glenn-hui-a** [comment]
Quick note, I was in the middle of going through this when I saw @nbanion 's comment - the data can be found at https://www.icpsr.umich.edu/web/ICPSR/studies/31461/versions/V2# , Download (I chose delimited). Generally concur with your assessement otherwise.

**Comment by nbanion** [comment]
@glenn-hui-a , thanks for looking. Were you actually able to find a delimited file in the download?

When I tried the same process, I only see two `.pdf` files, two `.html` files, and two `.txt` files with a small amount of metadata. If the issue persists and we want to use these data, then we might try to look up the maintainer of the collection.

**Comment by glenn-hui-a** [comment]
Yes, I found one with three .tsv files (about 600, 1200, 5000 records each). I can put them in the dropbox today or tomorrow if that helps.
