### ISSUE TITLE
Elections Calendar Data (US) and User Requirements

### ISSUE THREAD

**Issue by csmcallister** [DataKind-DC/ifes-elections#36]
## Elections Calendar Data

Heading over to [data.gov](https://www.data.gov/) and searching for "elections", I found [Oregon's election calendar](https://catalog.data.gov/dataset/oregon-elections-calendar). 

Here are a few rows:

```csv

Date | Description of Event | Reference | End Date
01/07/2021 12:00:00 AM | Last day for governing body to file or withdraw notice of measure election and any required explanatory statement. (March Election) | 254.095; 254.103; 255.085; OAR 165-022-0010 | 01/07/2021 12:00:00 AM
01/11/2021 12:00:00 AM | Last day to file candidate statements for county voters' pamphlet, if county producing a voters' pamphlet. (March Election) | OAR 165-022-0010 | 01/11/2021 12:00:00 AM
01/11/2021 12:00:00 AM | Last day to file measure arguments for county voters' pamphlet, if county producing a voters' pamphlet. (March Election) | OAR 165-022-0010 | 01/11/2021 12:00:00 AM
01/15/2021 12:00:00 AM | Material submitted for county voters' pamphlet available for public inspection. (March Election) | 251.43 | 01/15/2021 12:00:00 AM
```

Some googling might unearth similar datasets for other states. The same might exist for foreign countries. However, even if we had this data for every state/country, it's unclear to me how'd we use it together as comparing election "events" across borders might be apples-to-oranges so to speak. To me, this begs a larger, more existential question for this project: what do we want to accomplish?

## Requirements Gathering

What does IFES hope to achieve? The readme mentions adding interactive visuals to electionguide.org, but to what end? In my experience, we'd do well to start with some user research, polling our partner org to gather some user requirements. The simplest form of this would be developing some distinct personas for IFES and getting people to provide some user stories in the following format:

```
As a <persona>, I want <a goal/desire> so that <benefit>.
```

A simple example, with a few roles: 

- **As an election data analyst, I want to know which countries have a national holiday on election day so that I can use that information in a predictive model**
- **As a marketing analyst, I want a slick visual to put on our website so that the public can see the results/data created by our data analyst using the national holiday data**

## Suggestion

If we're able to get some folks from IFES into a (virtual) room, we could have a workshop to generate personas and related user stories. If not, maybe we can flesh out some that we think would be interesting to IFES.

**Comment by nbanion** [comment]
Excellent suggestions. As you note, we are still in the discovery phase, and I think these requirements gathering steps complement the idea generation efforts we discussed at the DataJam. We briefly discussed audiences at the initial scoping meeting; my read is that our partners would appreciate just seeing what is possible. Perhaps we can prompt them for user stories and use some of our own ideas to get the creativity flowing.

**Comment by jhgeorgi** [comment]
I really like the idea of phrasing questions/goals in terms of what different persona need or want. Might also want to look at what the voters want - where/how/when to vote, registration, safety, etc

**Comment by csmcallister** [comment]
In the interim, is our game plan to start reviewing datasets from the open issues to see what's possible? Then, once we have something compelling, perhaps we'd broach the subject of harder requirements gathering with the partners?

**Comment by nbanion** [comment]
Essentially yes.

Our top priority is partner-generated requirements gathering, and we should not waste time guessing what they want. But until we can sit down with IFES, I think it's worthwhile to brainstorm some thought-provoking examples. We don't need to be exhaustive, and we should recognize that these initial ideas will probably not survive intact. Just want to get us and them thinking.

Do you see value in that effort? Significant risk of putting our thumb on the scales?

**Comment by nbanion** [comment]
Here is an [example](https://github.com/DataKind-DC/ifes-elections/issues/28#issuecomment-785083186). Not real sophisticated, just a conversation starter.

I think that election calendars like the one identified here could produce some good ideas too.

**Comment by nbanion** [comment]
We had a successful requirements gathering meeting last week. Will continue the requirements conversation elsewhere.

Also, I moved the assessment of election calendar data to issue #37 .
