### ISSUE TITLE
What do the IFES election .xlsx files represent?

### ISSUE THREAD

**Issue by nbanion** [DataKind-DC/ifes-elections#39]
IFES election data are distributed in tens or hundreds of `.xlsx` files. What does each file represent? Is there a pattern?

Glancing at a couple files, each appears to have one sheet with data for a single election. The naming conventions are not totally uniform, but they seem to indicate different countries, elections (e.g. presidential, parliamentary), and dates.

**Comment by glenn-hui-a** [comment]
To add to above: There are 76 files in the Data Collection Forms 2020 Countries.zip, each corresponding to a one observation (row after transformation), as Nate suggests. 

About 10 countries appear multiple times; almost all of these are different elections (eg, one is national council, the other is presidential), often different years. Only a couple are just duplicates.

**Comment by nbanion** [comment]
Do you happen to have a list of the duplicates?

**Comment by nbanion** [comment]
Thanks for investigating. We've done enough for now.
