### ISSUE TITLE
Plan project infrastructure.

### ISSUE THREAD

**Issue by nbanion** [DataKind-DC/ifes-elections#4]
How do we want to organize our code?

My first choice would be a Python package that borrows from the [Cookiecutter Data Science](https://drivendata.github.io/cookiecutter-data-science/) template. This package would have reusable pieces for downloading, processing, and visualizing data. Curious to hear others' preferences.

I figure volunteers can use whatever software they like to draft new visuals. This work will probably happen in disposable notebooks. When we decide to go forward with a visual, then we can translate it to fit the package.

We could keep API keys on Google Drive. We could store data there too, but only if there isn't an easy way for others to download the data directly to their local repositories via the API.

**Comment by sramchandani** [comment]
I think for this small of a data set local or Google Drive is sufficient as this architecture gives us the performance edge of having data and processing on the same vicinity or machine

API keys via restricted sharing Google Drive will work for now.

I think when we go to Prod we may have to think about something else.
