### ISSUE TITLE
Do IFES elections .xlsx data have dates for events in the electoral cycle?

### ISSUE THREAD

**Issue by nbanion** [DataKind-DC/ifes-elections#41]
What variables in the IFES elections `.xlsx` files provide dates for events in the electoral cycle? How frequently do they have values? Are the values datetimes? Dates? Free text? A mix? **Bottom line: Are the date data usable?**

On #5 we did this analysis for the data available through the API and found big gaps. Interested to know if the raw `.xlsx` files offer anything different. Feel free to follow the old approach.

**Comment by nbanion** [comment]
The data are in the Google Drive under `Data/IFES Data Excel Sheets/`. Each `.xlsx` workbook seems to represent an election. I could imagine most of the data from a given workbook eventually occupying a single row of a tidier dataset.

The raw workbooks are organized for data entry. Each row is a field. The first few columns describe the field, and the most important user-entered values appear to be in column F. At a glance, it looks like rows, 9, 10, 11, 12, 22, 23, 25, 26, 28, 29, 31, 32, 35, 36, 39, and 40 could have date information. It's plausible that we want the same cells from each of the workbooks, but that assumption is probably worth testing.

Assuming the assumption holds, you might loop through the raw data paths, extracting values from each one, and then organizing the contents in a dataframe where they will be easier to examine.

**Comment by nbanion** [comment]
@glenn-hui-a , following up on a Slack conversation about extracting data:

First, if you already have a messy way to extract critical fields from source data, then that is probably enough for now. This exploratory analysis will help us know if it is worth it to work the kinks out.

In case it is useful, this R prototype seems to do pretty well for the first five cases. It throws an error on the full list of `.xlsx` files because at least one doesn't have the right column names. Downstream you would still need to handle dtypes, which are all character in the output.

```R
library(readxl)
library(tidyverse)

#' Extract a row of data from a source file
#' 
#' @param x A source data frame.
#' @return A named vector of values corresponding to a row.
extract <- function(x) {
  result <- x$`Election Data - Consultant Entries`
  names(result) <- x$`Field Name`
  result
}

# Paths to source data (edit the glob as needed).
paths <- Sys.glob("a/glob/leading/to/your/*.xlsx")

# Read rows from source data.
paths[1:5] %>% 
  map(read_excel, skip = 4, n_max = 44) %>% 
  map_dfr(extract)

```

**Comment by glenn-hui-a** [comment]
Hi team - I still intend to turn this into something more functional and apply it across all date variables listed below, but in case someone else just wants to take over, I'm just going to dump the working code I have so far. 

```r
require (tidyverse)
require (readxl)
require (lubridate)
library(tibble)

#' Extract a row of data from a source file
#' 
#' @param x A source data frame.
#' @return A named list of values corresponding to a row.
extract <- function(x) {
  result <- x %>% pull(`Election Data - Consultant Entries`)
  names(result) <- x %>% pull(`Field Name`)
  result
}

# Paths to source data (edit the glob as needed).
paths <- Sys.glob("C:/Users/username/Documents/Work/IFES/*.xlsx")

# Read rows from source data. Can delete or merge columns 42-43 later.
readall <- paths %>% 
  map(read_excel, skip = 4, n_max = 44) %>% 
  map_dfr(extract)

newdates <- readall  %>%
  add_column(election_range_start_date_dv = 
    if_else(grepl("^[0-9]{2}[[:punct:]][0-9]{2}[[:punct:]][0-9]{4}.*",readall$election_range_start_date), 
      substr((readall$election_range_start_date), 1, 10), 
      if_else( grepl("^[0-9]{4}[[:punct:]][0-9]{2}[[:punct:]][0-9]{2}.*",readall$election_range_start_date), 
      substr((readall$election_range_start_date), 1, 10), 
        if_else( grepl("^[0-9]{5}&*",readall$election_range_start_date), 
        as.character(as.Date(as.numeric(readall$election_range_start_date), origin = "1899-12-30")), 
          if_else(grepl("^[0-9]{4}\\s+.*",readall$election_range_start_date), 
          substr((readall$election_range_start_date), 1, 4), "NA"
          )
        )
      )
    )
  )

# readall$election_range_end_date
# readall$election_declared_start_date
# readall$election_declared_end_date
# readall$election_candidate_filing_deadline
# readall$voter_registration_deadline
# readall$election_blackout_end_date
# readall$election_blackout_start_date
# readall$`in-person-voting-methods.start`
# readall$`in-person-voting-methods.end`

```

**Comment by nbanion** [comment]
Couple updates. Will push the implementation sometime soon:

First, I found the one source file that doesn't read cleanly using the `extract` function described above. It is `Nepal House of Representatives 2021_202120210114(050148).xlsx`, and it doesn't follow the typical format.

Second, using "election_range_start_date" as an example, I identified four main classes of date data: missing values, pure numeric values (likely datetimes originally), text with no numbers (essentially missing), and text with numbers (possibly parse-able, as Glenn started to do above). Best case, it looks like maybe 2/3 of cases would have useable date values. 

```R
# A tibble: 4 x 2
  type               n
  <chr>          <int>
1 missing           36
2 number            59
3 text               9
4 text w/ number    21
```

I also have some thoughts about the date parsing workflow. We can talk soon.

**Comment by nbanion** [comment]
I am not convinced we have enough sufficiently populated date fields to support our analysis. See `notebooks/2021-04-20-explore.html` on the drive for details.

![image](https://user-images.githubusercontent.com/16766406/115639929-ccab8200-a2e3-11eb-8b11-489d31de93eb.png)
