### ISSUE TITLE
What years do the IFES elections .xlsx data cover?

### ISSUE THREAD

**Issue by nbanion** [DataKind-DC/ifes-elections#43]
The ElectionGuide API election data primarily covered 2020 and 2021 (see #20 ). Do the IFES election `.xlsx` data cover the same time frame?

**Comment by glenn-hui-a** [comment]
Data Collection Forms 2020 Countries.zip has 76 files/observations, indeed all 2020 or 2020-focused. There seem to be a couple of elections that are actually 2021. 

About 10 files are corresponding legislative elections - eg, there is a file for each of 2020 Poland presidential and 2023 Poland senate. Latest year appears to be 2024.

**Comment by nbanion** [comment]
Great. So these are all recent or pending elections.
