### ISSUE TITLE
What data types are available in the PEI data?

### ISSUE THREAD

**Issue by nbanion** [DataKind-DC/ifes-elections#50]
Many of the fields in the [PEI data](https://dataverse.harvard.edu/dataverse/PEI) are categorical ratings. How do these variables work? Are there other types of variables too? If so, what interesting ones do you see?

**Comment by nbanion** [comment]
More to say, but I wanted to quickly note the main questionnaire sections from the codebook (p5-29).

The first sections provide basic background:

- identifiers: Variables to identify experts, elections, countries, and years of data collection.
- country data: Background on the country of study.

The third section summarizes overall integrity:

- overall integrity: Aggregated integrity scores, confidence intervals, ratings, trends, etc.

The next sections provide details for specific parts of the electoral cycle. Each section includes several categorical questions and numeric indices that summarize the responses:

- electoral procedures
- boundaries for voting districts
- voter registration
- party and candidate registration
- media coverage
- campaign finance
- voting process
- the vote count
- voting results
- election authorities

The next sections include details about the experts who provide data, as well as their global opinions about elections, organizations, and special topics:

- general election questions
- organizational confidence
- expert background
- vignettes
- rotating battery

The final section describes election results:

- election result: turnout, vote shares, changes in power, etc.

The detailed categorical questions at the heart of the survey seem to be marked [P] for positive statements (e.g., "The election was fair.") and [N] for negative statements ("Voters were suppressed"). The responses typically include the following, though _not_ always in the same order:

1. Strongly Disagree
2. Disagree
3. Neither Agree nor Disagree
4. Agree
5. Strongly Agree

**Comment by jhgeorgi** [comment]
I really think you've covered it. When I did a quick analysis of the data, I didn't use them as categorical data points but as values in the third section.  I think that it might be possible to use the categorical values in the last section to determine the need for oversite for specific election phases if IFES wants that. I could sit around playing with the data all day, but doubt that I'd provide any information for the IFES project.

The biggest drawback to this data is the lack of dates for specific stages of the election cycle. 

What may be more useful are the resources and research listed on the report's source, Election Integrity Project, website: https://www.electoralintegrityproject.com/

**Comment by jhgeorgi** [comment]
Would it be of value to match the countries in this dataset with the countries in the IFES dataset, then show in each stage with dates of the IFES data what the degree of election integrity was from the PEI data???

**Comment by nbanion** [comment]
We opened #54 for this purpose. Thanks for reviewing!
