### ISSUE TITLE
What literature references the PEI data?

### ISSUE THREAD

**Issue by nbanion** [DataKind-DC/ifes-elections#52]
Has any literature referenced the [PEI data](https://dataverse.harvard.edu/dataverse/PEI)? What kinds of questions do they try to answer? Are there any resources that could help us think about our motivating questions?

If you find any useful articles, you can save them on the project Google Drive folder.

**Comment by nbanion** [comment]
Here is one:

https://www.cambridge.org/core/journals/ps-political-science-and-politics/article/measuring-electoral-integrity-around-the-world-a-new-dataset/506F05DEF195C4A73DD1C937591B2071

**Comment by glenn-hui-a** [comment]
Including that one, there are a lot of articles by P Norris (also a primary author on the PEI Index) citing and using this dataset, mostly with a US focus.

https://www.helleniscope.com/wp-content/uploads/2020/12/ElectoralIntegrityWorldwide-1.pdf looks like an updated version of the above - i.e. a good summary of the dataset's findings - and may be worth skimming / reading in its entirety. (Edit: I've started and will post a summary tomorrowish.)

**Comment by nbanion** [comment]
Great find, complete with interesting graphics! Figure 5 is an example of how we can compare different electoral phases for multiple elections or countries.

**Comment by nbanion** [comment]
The 2019 report employs the following approaches:

1. Summarize overall country-level index scores.
2. Subset the summary by region and regime type.
3. Summarize the high and low performing electoral stages.
4. Identify the drivers behind the score of a specific electoral phase.
5. Pair indices with subject matter expertise for country case studies.

Ideas for building on this work:

- Different graphics for the star charts, which I find hard to read.
- Focus on case studies that IFES is interested in.
- Explore trends in indices over time.

**Comment by glenn-hui-a** [comment]
I just finished going through it myself, thanks for the summary. I'm looking over again what IFES is looking for to see how else this dataset might be useful to them.

**Comment by jhgeorgi** [comment]
If you have access to Academic Search Premier, you can do a search for citations to an article or an author(s). Don't know if that will help.

**Comment by nbanion** [comment]
Closing for now. Thanks for your help gathering background.
